services:
  frontend:
    build:
      target: prod
      args:
        VITE_MAXMETRICS_API_URL: https://${BACKEND_SERVER_NAME:-api.maxmetrics.ca}

  backend:
    build:
      target: frankenphp_prod
