<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260619004026 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds new account table and alter profile for the one-to-one relationship with account table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE account (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL)');
        $this->addSql('ALTER TABLE profile ADD account_id INTEGER DEFAULT NULL');
        $this->addSql('ALTER TABLE profile ADD CONSTRAINT FK_8157AA0F9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8157AA0F9B6B5FBA ON profile (account_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE profile DROP CONSTRAINT FK_8157AA0F9B6B5FBA');
        $this->addSql('DROP INDEX UNIQ_8157AA0F9B6B5FBA');
        $this->addSql('ALTER TABLE profile DROP account_id');
        $this->addSql('DROP TABLE account');
    }
}
